### ISSUE TITLE
前端可以用material design

### ISSUE THREAD

**Issue by maxchu2021** [Keanux/keanux-personal#34]

**Comment by dca** [comment]
推薦 https://github.com/callemall/material-ui

**Comment by maxchu2021** [comment]
這很不錯喔，想問一下，這樣是不是就要完全參照他的html去設計啊？如果想要改Theme的話是不是會很麻煩？

**Comment by dca** [comment]
我也是昨天小玩一下而已，主要是因為他完全就是用 React Component 的角度來實現，整體的用法跟擴展方法都跟自己寫 Component 一樣直覺，應該是可以試試
