### ISSUE TITLE
remove JQuery dependency

### ISSUE THREAD

**Issue by jhen0409** [Keanux/keanux-personal#39]
目前看起來 jquery 好像只拿來用 AJAX, 會不會有點大材小用?

可以的話用 fetch 可能會是不錯的選擇
目前有 https://github.com/github/fetch 這個 polyfill，以後所有瀏覽器應該也會陸續都支援 fetch

**Comment by dca** [comment]
有過同樣想法 :+1:

**Comment by appleboy** [comment]
:+1:
