### ISSUE TITLE
Redefind promise causing jshint error

### ISSUE THREAD

**Issue by kirkchen** [Keanux/keanux-personal#50]
由於在[./data/seed.js](https://github.com/Keanux/keanux-personal/blob/master/server/data/seed.js#L3)中使用了bluebird的promise來進行非同步，
導致JsHint跳出錯誤提示 (#49)，警告我們複寫了Global的Promise，
在暫時不升為ES6的考量下 （為了降低教學門檻），
是否有較好的解決方法？

參考 @dca 的建議，解決方案如下
a. 改名
b. 替換 es6 內建的 global.Promise
c. (區域or全域)忽略 redefine 問題

@appleboy @keanyc 有其他的建議嗎？

**Comment by appleboy** [comment]
`為了降低教學門檻` 就 c. 吧

a. 不適合改名
b. 增加入學門檻

**Comment by dca** [comment]
在不使用 es6 的前提下，個人認為 Promise 的概念還是不可或缺的。原因是同樣的概念已經頻繁出現在目前我們使用(慣用)的各個模組中，例如 `jQuery.ajax` `mongoose` `fetch`

**Comment by kirkchen** [comment]
如果大家都同意的話，
我就先將jshint中關於Promise Redefine的檢查透過以下方式移除

在.jshintrc中加入predef設定

```
{
  "predef": [ "-Promise" ]
}
```
