### ISSUE TITLE
don't think it's good to put all css in one file

### ISSUE THREAD

**Issue by zzz6519003** [Keanux/keanux-personal#55]
react prefer component XD

**Comment by AnthonyTsang** [comment]
Despite component styling is an exciting idea, it has some problems. 
1, Both style library and inline style are not supporting pseudo class. 
2, Least reusability. 
3, Responsive layout may become harder to make.
4, Harder to change on browser. We cannot change a style in css class in browser to see the whole impact to the page.

**Comment by zzz6519003** [comment]
3, Responsive layout may become harder to make.

can u give a example 
XD
:beer:

**Comment by AnthonyTsang** [comment]
Say we cannot make responsive style inline. So, after all we still need element class and id for the style. 2 style system working tgt is not a good idea. 

But hey, I found something cool :smile:  http://caniuse.com/#feat=style-scoped

I believe the in-component styling will work years later.

**Comment by zzz6519003** [comment]
awesome site!  thx!
